kumuluzee:
  name: nakupovalniseznami
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/NakupovalniSeznamiDS
      connection-url: jdbc:postgresql://localhost:5432/nakupovalniseznami
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        jndi-name: jdbc/NakupovalniSeznamiDS
      disk-space-health-check:
        threshold: 100000000
predlogeapiurl: http://localhost:8081/v1